KiemTra_TrinhDuDat/Controllers/HocPhansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KiemTra_TrinhDuDat.Models;

namespace KiemTra_TrinhDuDat.Controllers
{
    public class HocPhansController : Controller
    {
        
        MyDataDataContext db = new MyDataDataContext();
        // GET: HocPhans
        public ActionResult Index()
        {
            return View(db.HocPhans.ToList());
        }
        //Dang ky hoc phan
        public ActionResult Dk_Hocphan(string id)
        {
            HocPhan hocPhan = db.HocPhans.SingleOrDefault(p => p.MaHP == id);
            if(hocPhan == null)
            {
                return HttpNotFound();
            }
            return View(hocPhan);
        }

        //Gio dang ky hoc phan
     }
}

KiemTra_TrinhDuDat/Views/HocPhans/Create.cshtml
@model KiemTra_TrinhDuDat.Models.HocPhan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HocPhan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaHP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaHP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaHP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenHP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoTinChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoTinChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoTinChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KiemTra_TrinhDuDat/Views/HocPhans/Delete.cshtml
@model KiemTra_TrinhDuDat.Models.HocPhan

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HocPhan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenHP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoTinChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTinChi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KiemTra_TrinhDuDat/Views/HocPhans/Details.cshtml
@model KiemTra_TrinhDuDat.Models.HocPhan

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>HocPhan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenHP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoTinChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTinChi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaHP }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KiemTra_TrinhDuDat/Views/HocPhans/Dk_Hocphan.cshtml
@model KiemTra_TrinhDuDat.Models.HocPhan

@{
    ViewBag.Title = "Dk_Hocphan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<p  style="font-size:24px">Bạn đã đăng ký học phần <strong>@Model.TenHP</strong> với số tín chỉ @Model.SoTinChi </p>

KiemTra_TrinhDuDat/Views/HocPhans/Edit.cshtml
@model KiemTra_TrinhDuDat.Models.HocPhan

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HocPhan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaHP)

        <div class="form-group">
            @Html.LabelFor(model => model.TenHP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoTinChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoTinChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoTinChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KiemTra_TrinhDuDat/Views/HocPhans/Index.cshtml
@model IEnumerable<KiemTra_TrinhDuDat.Models.HocPhan>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaHP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenHP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoTinChi)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.MaHP)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TenHP)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SoTinChi)
    </td>
    <td>
      <div class="DatMua">
          <a class="btn btn-success" href="@Url.Action("ThemGioHang", "GioHang",
            new { @id = item.MaHP, @strURL = Request.Url.ToString() })">Đăng ký</a>
      </div>
    </td>
</tr>
}

</table>
@*<a href="@Url.Action("Dk_Hocphan","HocPhans", new { id=item.MaHP})" class="btn btn-primary">Đăng ký</a>*@